---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(nycflights13)
```

```{r}
flights
planes
```

## Q1 Is there a relationship between the age of a plane and its departure delays?

```{r}
plane_ages <- planes %>%
  mutate(age = 2013 - year) %>%
  select(tailnum, age)

flights %>% 
  select(dep_delay, tailnum) %>%
  inner_join(plane_ages) %>%
  ggplot(mapping = aes(x=age, y=dep_delay)) + 
  geom_smooth()

# ggplot()
```
```{r}
flights %>% 
  # select(dep_delay, tailnum) %>%
  left_join(plane_ages, by="tailnum") %>%
  group_by(age) %>%
  summarize(mean_delay = mean(dep_delay, na.rm=TRUE)) %>%
  ggplot(mapping = aes(x=age, y=mean_delay)) + 
  geom_point() +
  geom_line()
```

## Q2: Add the location of the origin and destination (i.e. the lat and lon) to flights

```{r}
airports_lite <- airports %>%
  select(faa, lat, lon)

flights %>%
  left_join(y = airports_lite, by = c(dest = "faa") ) %>%
  left_join(y = airports_lite, by = c(origin = "faa"), suffix = c(".dest", ".origin"))
```

